channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - geocat-viz=2020.2.18.1
  - netcdf4
  - cartopy
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - pip
  - pip:
    - matplotlib
    - mock
    - pillow
