channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - geocat-viz=2020.1.28.0
  - netcdf4
  - cartopy
  - pip
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - matplotlib
    - sphinx-gallery
    - cmaps
    - mock
    - pillow
