channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - netcdf4
  - cartopy
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    - matplotlib
    - sphinx-gallery
